name: python_userfork
description: ''
version: 0.0.1
author: abhisheks+e2etests@simpledatalabs.com
language: python
buildSystem: wheel
pipelines:
  pipelines/python_userfork_PIPELINE:
    name: python_userfork_PIPELINE
    description: python_userfork_PIPELINE
    author: abhisheks+e2etests@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-06-14 15:51:50'
    datasets:
      inputs:
      - 163/datasets/dataset_cust_in
      outputs: []
    dependencies: {}
datasets:
  datasets/dataset_cust_in:
    name: dataset_cust_in
    description: ''
    author: abhisheks+e2etests@simpledatalabs.com
    createdAt: '2022-06-14 15:55:58'
    physicalDatasets:
      dev:
        fabricId: 29
        datasetType: File
        description: ''
        author: abhisheks+e2etests@simpledatalabs.com
        createdAt: '2022-06-14 15:55:58'
templates:
  templates/wheel:
    name: wheel
    description: null
    author: abhisheks+e2etests@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-06-14 15:47:56'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
jobs:
  jobs/python_userfork_JOB:
    name: python_userfork_JOB
    description: ''
    fabricUID: 29
    scheduler:
      Databricks: {}
    jobSize: small
    scheduleCron: 0 0 * ? * * 2050
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - 163/pipelines/python_userfork_PIPELINE
    enabled: null
    createdAt: '2022-06-14 16:15:30'
    author: abhisheks+e2etests@simpledatalabs.com
libraries: []
subgraphs: {}
dependencies:
- name: mysql
  coordinates: mysql:mysql-connector-java:8.0.29
  exclusions: []
  type: coordinates
  enabled: false
- repo: https://repo.maven.apache.org/maven2/
  coordinates: org.springframework:spring-beans:5.3.19
  name: spring
  exclusions:
  - commons-logging:commons-logging
  type: coordinates
  enabled: false
- package: matplotlib==3.5.2
  name: matplotlib
  type: pypi
  enabled: false
- package: pandas>=1.4.2
  name: pandas
  type: pypi
  enabled: false
- package: numpy==1.22.*
  name: numpy
  type: pypi
  enabled: false
- package: requests~=2.28.0
  name: requests
  type: pypi
  enabled: false
- package: torch==1.11.0
  name: torch
  type: pypi
  enabled: false
template: "version: \"1\"\npipeline:\n  path: /setup.py\n  content: |\n    from setuptools\
  \ import setup, find_packages\n    \n    setup(\n      name='@{buildMetadata.pipelineMetadata.name}',\n\
  \      version='1.0',\n      packages=find_packages(include=('job*',)),\n      description='@{buildMetadata.pipelineMetadata.description}',\n\
  \      install_requires=[\n        @{dependencies.collect{case x:PyPiDependency\
  \ ⇒ x}.map(x => s\"'${x.`package`}'\").map(x => s\"$x,\\n\")}\n        'prophecy-libs==@{buildMetadata.prophecyLibsVersion}'\n\
  \      ],\n      entry_points={\n        'console_scripts': [\n          'main =\
  \ job.pipeline:main',\n        ],\n      },\n      tests_require=['pytest', 'pytest-html']\n\
  \    )\n\n"
