name: Project-Automated-FORKED-GITHUB
description: User fork
version: 0.0.1
author: abhisheks+e2etests@simpledatalabs.com
pipelines:
  pipelines/Workflow-Automated-GITHUB-FORK-1649079164232:
    name: Workflow-Automated-GITHUB-FORK-1649079164232
    description: automation workflow
    author: abhisheks+e2etests@simpledatalabs.com
    mode: batch
    language: scala
    createdAt: '2022-04-04 13:33:10'
    datasets:
      inputs:
      - 370/datasets/customer_data_json
      outputs: []
    dependencies: {}
datasets:
  datasets/customer_data_json:
    name: customer_data_json
    description: ''
    author: abhisheks+e2etests@simpledatalabs.com
    createdAt: '2022-04-04 13:34:01'
    physicalDatasets:
      dev:
        fabricId: 40
        datasetType: File
        description: ''
        author: abhisheks+e2etests@simpledatalabs.com
        createdAt: '2022-04-04 13:34:01'
jobs: {}
libraries: []
